# Generated by Django 2.1.2 on 2018-10-02 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_orcamento.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_da_mobilia', models.CharField(max_length=64)),
                ('largura', models.FloatField()),
                ('altura', models.FloatField()),
                ('profundidade', models.FloatField()),
                ('tipo_do_puxador', models.CharField(max_length=64)),
                ('pintura', models.CharField(max_length=64)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_orcamento.Orcamento')),
            ],
        ),
    ]
